--- 
spring: 
  application: 
    name: test
server: 
  port: ${PORT:${SERVER_PORT:0}}
nationalities: to,pass,the,test

--- 
spring: 
  profiles: nationality
  application: 
    name: nationality
nationalities: italiano,inglese,americano,francese,giapponese
server: 
  port: 8081
  
--- 