--- 
spring: 
  application: 
    name: test
server: 
  port: ${PORT:${SERVER_PORT:0}}
uri:
  nationality: uri
  award: uri
--- 
spring: 
  profiles: actor
  application: 
    name: actor
uri:
  nationality: http://localhost:8081/S1/
  award: http://localhost:8082/S2/
    
server: 
  port: 8080
  
--- 