--- 
spring: 
  application: 
    name: test
server: 
  port: ${PORT:${SERVER_PORT:0}}

--- 
spring: 
  profiles: actor
  application: 
    name: actor

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

server: 
  port: 8080
  
--- 